**EDX python lessons**

**Errors and Exceptions**
The try command compels the program to run the code while checking for errors, in this case a value error incase the input is not an integer.
If there is no error the exception is not triggered therefore the else 
command is executed. The exception is triggered when a value error occurs,
i.e. by entering a value that is not an integer, executing the alternative command

The 'break' command can be used alternatively after the exception to break the infinite loop 'return' is a better alternative that can be used in a function to break out of a loop within the function while returning a value as well.

'pass' can be used as well to catch the error without necessarily indicating to the user
